# Generated by Django 5.2.6 on 2025-10-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_task_options_commonboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='common_board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.commonboard'),
        ),
    ]
