# Generated by Django 4.2.11 on 2025-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due_date'),
        ),
    ]
