# Generated by Django 5.2.7 on 2025-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_taskgroup_common_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonboard',
            name='alerts',
            field=models.BooleanField(default=True, verbose_name='alerts'),
        ),
    ]
