# Generated by Django 5.2.7 on 2025-10-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=36, unique=True, verbose_name='link_id')),
                ('expiration', models.DateField(verbose_name='expiration')),
                ('common_board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.commonboard')),
            ],
        ),
    ]
