# Generated by Django 5.2.7 on 2025-11-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='link_id',
        ),
    ]
