# Generated by Django 5.2.7 on 2025-11-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_invite_expiration_remove_invite_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonboard',
            name='alerts',
        ),
    ]
