# Generated by Django 5.2.7 on 2025-11-11 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_commonboard_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='ViewSetting',
        ),
        migrations.CreateModel(
            name='CommonBoardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_alerts', models.BooleanField(default=True, verbose_name='show_alerts')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.commonboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
