# Generated by Django 5.2.7 on 2025-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_viewsetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsetting',
            name='display_description',
            field=models.BooleanField(default=False, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='viewsetting',
            name='display_due_date',
            field=models.BooleanField(default=False, verbose_name='due_date'),
        ),
    ]
