# Generated by Django 5.2.7 on 2025-11-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_viewsetting_display_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewsetting',
            name='view',
        ),
    ]
